# Desired classes with preferences
[preferences]
classes_taken = ["CMPT 332", "PHYS 212", "MATH 223"]
classes_wanted = ["CMPT 431", "CMPT 342"]

# Schedule of available classes
# Each course can be represented as a nested table for better organization

[[schedule]]
code = "CMPT 332"
name = "Operating Systems"
section = "A1"
days = ["Monday", "Wednesday", "Friday"]
start_time = "09:00"
end_time = "10:00"

[[schedule]]
code = "CMPT 342"
name = "Operating Systems"
section = "A1"
days = ["Monday", "Wednesday", "Friday"]
start_time = "09:00"
end_time = "10:00"

[[schedule]]
code = "PHYS 212"
name = "Electricity and Magnetism"
section = "B2"
days = ["Tuesday", "Thursday"]
start_time = "11:00"
end_time = "12:30"

[[schedule]]
code = "MATH 223"
name = "Calculus III"
section = "A3"
days = ["Monday", "Wednesday"]
start_time = "13:00"
end_time = "14:30"

[[schedule]]
code = "CMPT 431"
name = "Computer Networks"
section = "A1"
days = ["Tuesday", "Thursday"]
start_time = "09:00"
end_time = "10:30"

